targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
      build_vm_compilers|entrypoint:
        generate_for:
          - lib/**.dart
          - test/**.dart
          - bin/**.dart
