name: flutter_dalk_sdk
description: A new Flutter package project.
version: 0.0.1
documentation: https://dalk.io/doc/api/
issue_tracker: https://github.com/Dalk-io/sdk/issues
repository: https://github.com/Dalk-io/sdk/packages/flutter
homepage: https://dalk.io

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter_hooks: ^0.9.0
  dash_chat: ^1.1.2
  provider: ^4.0.5+1
  infinite_widgets: ^1.0.1
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  dalk_sdk:
    path: '../dart'
  flutter:
    sdk: flutter

dev_dependencies:
  mobx_codegen: ^1.0.3
  pedantic: ^1.8.0+1
  build_runner:
  flutter_test:
    sdk: flutter
