name: flutter_dalk_sdk
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dalk_sdk:
    path: '../dart'
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
