# This is a basic workflow to help you get started with Actions

name: Check on PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_dart_sdk:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.3.0
      with:
        channel: beta

    - name: Build deps
      run: pub get
      working-directory: ./packages/dart

    - name: Build generated code
      run: pub run build_runner build --delete-conflicting-outputs
      working-directory: ./packages/dart

    # Build source to flutter web
    - name: Run test
      run: pub run test
      working-directory: ./packages/dart

  build_flutter_sdk:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: beta

      - name: Build deps
        run: flutter pub get
        working-directory: ./packages/flutter

      - name: Build generated code
        run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: ./packages/flutter

      # Build source to flutter web
      - name: Test
        run: flutter test
        working-directory: ./packages/flutter

  build_dart_sdk_example:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: dev

      - name: Enable flutter web
        run: flutter config --enable-web

      - name: Build deps
        run: flutter pub get
        working-directory: ./packages/dart/example

      - name: Build generated code
        run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: ./packages/dart/example

      # Build source to flutter web
      - name: Build for web
        run: flutter build web
        working-directory: ./packages/dart/example

  build_flutter_sdk_example:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.0
        with:
          channel: dev

      - name: Enable flutter web
        run: flutter config --enable-web

      - name: Build deps
        run: flutter pub get
        working-directory: ./packages/flutter/example

      - name: Build generated code
        run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: ./packages/flutter/example

      # Build source to flutter web
      - name: Build for web
        run: flutter build web
        working-directory: ./packages/flutter/example
