# This is a basic workflow to help you get started with Actions

name: Deploy Dart SDK Production

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - "*.dart"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_deploy_to_production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.3.0

    - name: Format for pub score
      run: dartfmt -w .

    - name: Setup pub credentials
      run: |
        mkdir -p ~/.pub-cache
        echo "$PUB_INFO" > ~/.pub-cache/credentials.json
      shell: bash
      env:
        PUB_INFO: ${{secrets.PUB_INFO}}

    - name: Build deps
      run: pub get
      working-directory: ./packages/dart

    - name: Build generated code
      run: pub run build_runner build --delete-conflicting-outputs
      working-directory: ./packages/dart

    - name: Run test
      run: pub run test
      working-directory: ./packages/dart

    - name: Publish package
      run: pub publish -f
      working-directory: ./packages/dart
